logging:
  level:
    io.github.tiscs.scp: info
    # Fix https://github.com/springfox/springfox/issues/1100, https://github.com/swagger-api/swagger-core/issues/1568
    io.swagger.models.parameters.AbstractSerializableParameter: error
spring:
  datasource:
    username: ${SCP_MYSQL_USERNAME}
    password: ${SCP_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  devtools:
    add-properties: false
mybatis:
  type-aliases-package: io.github.tiscs.scp.entities
