logging:
  level:
    io.github.tiscs.scp: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.application.name}?useSSL=false&serverTimezone=GMT%2B8
  devtools:
    add-properties: true
    livereload:
      enabled: true