logging:
  level:
    io.github.tiscs.scp: info
    Exposed: warn
server:
  forward-headers-strategy: framework
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  devtools:
    add-properties: false
    livereload:
      enabled: false
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        input:
          content-type: application/json
          destination: ${spring.application.name}-input
          group: ${spring.application.name}
        output:
          content-type: application/json
          destination: ${spring.application.name}-output
      rabbit:
        bindings:
          default:
            producer:
              transacted: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
opentracing:
  jaeger:
    enabled: false
mybatis:
  type-aliases-package: io.github.tiscs.scp.models
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  packages-to-scan: io.github.tiscs.scp.controllers
