spring:
  datasource:
    username: ${SCP_MYSQL_USERNAME}
    password: ${SCP_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    io.github.tiscs.scp: info