logging:
  level:
    io.github.tiscs.scp: debug
    Exposed: debug
server:
  use-forward-headers: false
management:
  health:
    redis:
      enabled: false
spring:
  session:
    store-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}?currentSchema=public
  devtools:
    add-properties: true
    livereload:
      enabled: true
  cloud:
    config:
      allow-override: true
      override-system-properties: false
      override-none: true
feign:
  client:
    config:
      default:
        loggerLevel: full
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://localhost:14268/api/traces
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5hg2+KdJY82M+akmW6J2
          kKFghmJ7tk32r5s4B+5jIHSrX5YvS5FR3lkbMAzvI1yY5qkAxQTU7NmVclVjymd/
          BoT2gBzKhmXUmpevDnAUUDuGVXy9UIj/v86KKtPXPV2l5WpJuMX/xIrc/OT+Hbqk
          0QVkQSqG1MHNcbosmO6ONPvWioQkfY4HTnTshGizdhTUX7c4jnRY6fFYPFb9U1a8
          Zn+kECnnevV7yL87+/T4X8ch0tns7NlOKh7qoFsDlfJvGEPfCgIavEQbV6Bs4Gph
          6fwktoqGfdykO0lTbX0+qE/MnV65idkrbCENJNQHqnt8FPSTkIYYEdNKl2NQ/vQU
          XuSb/KlEEc/0xN+Jo3/O9MFWVQXiPKam3skdy8ciXYKKKR5t6tlRxlDXyGVHPpdF
          84Ci8l84dSnMea8sxiKwCytaDbhB8qWKz7Zpbx6DmW1DBDRxFxJsHKGw+t756RHD
          SrcwEyfP4O0G9GG4huUFNytBYxytdiKQo91PhJGk3vkRPNJiqDr9Pd3Rz+Kih3fO
          CKAdUmCuu6uxl3Te5swr0K4tTpfJ9d20omaFyVD+S4s9lwIb5GGhsStBUdwTeUpM
          VGbM/K9YcFbvdBEmr4GFepHk8g0Q9fXWjGqACAda4QVhl26k2EJw5vs2zFYO0H0N
          MHp19TQh759MFvW/ZQan+psCAwEAAQ==
          -----END PUBLIC KEY-----
    authorization:
      jwt:
        key-value: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIJJwIBAAKCAgEA5hg2+KdJY82M+akmW6J2kKFghmJ7tk32r5s4B+5jIHSrX5Yv
          S5FR3lkbMAzvI1yY5qkAxQTU7NmVclVjymd/BoT2gBzKhmXUmpevDnAUUDuGVXy9
          UIj/v86KKtPXPV2l5WpJuMX/xIrc/OT+Hbqk0QVkQSqG1MHNcbosmO6ONPvWioQk
          fY4HTnTshGizdhTUX7c4jnRY6fFYPFb9U1a8Zn+kECnnevV7yL87+/T4X8ch0tns
          7NlOKh7qoFsDlfJvGEPfCgIavEQbV6Bs4Gph6fwktoqGfdykO0lTbX0+qE/MnV65
          idkrbCENJNQHqnt8FPSTkIYYEdNKl2NQ/vQUXuSb/KlEEc/0xN+Jo3/O9MFWVQXi
          PKam3skdy8ciXYKKKR5t6tlRxlDXyGVHPpdF84Ci8l84dSnMea8sxiKwCytaDbhB
          8qWKz7Zpbx6DmW1DBDRxFxJsHKGw+t756RHDSrcwEyfP4O0G9GG4huUFNytBYxyt
          diKQo91PhJGk3vkRPNJiqDr9Pd3Rz+Kih3fOCKAdUmCuu6uxl3Te5swr0K4tTpfJ
          9d20omaFyVD+S4s9lwIb5GGhsStBUdwTeUpMVGbM/K9YcFbvdBEmr4GFepHk8g0Q
          9fXWjGqACAda4QVhl26k2EJw5vs2zFYO0H0NMHp19TQh759MFvW/ZQan+psCAwEA
          AQKCAgAT8vGBKW/ReVbJpoKu2y0QaQ1nWU6Ehcnne7ul5GMvwy3AgdLj6FuCvZL/
          3X82P6b6CJkKe9rCFjNA0Gpwd/ypYgnFHbnpYRbHuHLy+4CnXCHPc5suSlJyHMQZ
          5nf42A+0Dj0KChCcx7VVL71gcngrrx38EGXUOGFJhOys7bHiohr9s2s+f3ver4B6
          EmHM0Q2Apu/+WdQDpGsUAC7CdPisolBlHlz1aicrRnk65QhLtYYXM9G4zzZZrIiH
          Ep0C+RvsrKW/xmLvA7CjLkOCSXbnxHaiZOw4KVML2NWk3oD6MsD4u+e2Ld/35f2v
          vbpUa5RcdL/+fcHEed8ztOam1B6X2X1Dk+knO5rJbuesp0Gj47zpb9RTvVa11ndo
          iAtAjXkaO0AToq8nesMFdqRDE3UQtqATtBcR6RKORgn1Trxtg/kcS4VLGdXuy5/A
          UZSI9PcQYn+lyJXjddIU2SjOCxsp+Zmqamof4rtG8+QMzg3wANxDXKAqEfY9uMLb
          opZQm1vy/SXKjsHSGIoljRZ3vfSItnt3KD0MpZSqz1TOnLiKzgDo9TewLk0hetQO
          V2lRe5vOCZDexF50lkOx7Og1UHVz9aY1Qt3Apxl0TjCwut0pJ+ccvtCOTT5jn3WX
          GyszDbrjCMv0GOmg01bipvTM/laM2ToPsffpKptibDsjr+boQQKCAQEA+L1I1v3+
          +EXXX09aVX89vKJkQuB5hH5mfb9zXVUrqLYvo9AeBwXkD8IMmQsf5lcngTlur1cN
          Kzxkog9uN5mDto30JWfCZIIWsSgoFeeBNYkMXJXBo0YXKSakNw3A5F+XCmGM4Q0u
          5IvGVEuE5i5m4pZtGxWvnvwCwhZXhIaC8AB3HXMNRT8rb1ABwTG1LBJlqY9TMHTp
          X0ZhoC38m1eSpKCFpkj9i/XPpugl7xYY1Ul2AKel1rhKVKhUgvgz04Kkugc42R5Z
          lh6ePMvMoFYH9XJLINERXthZgVCofPRKcktZ5cxha7MFvfPEVXyG3mXyE+4h6YcC
          YnFogZZxmwHbKwKCAQEA7M+bKy2xT2/8HMmURjtjg+aedW7+cLaE206IA/zs+Y/d
          h3z14H+CSrQ5sgaEhu+Ckp1nBlmzrfv46Q9+/pBBVVIrkSilQUIA8pPo/WXTIGMh
          2o7/o8l6LN6PdXodXkOqFsqPGn4b323bo9zkWEi1fEnQNeCkcnIhvKw6O2/avlcK
          rlKmBMYNo8AoGBGJ603DcltIGZljKmNxe642zgR42p2uoDI94k+6gtAjAD57eic8
          m3/xiJqacDiQeBkZR85xcy9sBasyjvsIfKJNI2ujw0XWrxjTTELpv8Uy/hZKewfJ
          2US8Lw+e4BofQezZeQIcQlsW9kfilN2y4ux9x/vmUQKCAQAQ+CDbAfL+Dw21Y91+
          zbJxhwaeBWBk6JanZ4NAT8ottVgkrdMOmZlIde2UF00y0qlQSJHDhoXQeEtJPxI+
          2stAjgik8KIzZyiTJ3EspWGMPHBKdLEEKYj09rznQJnzOo48WBFbXSHg16RNJeXI
          Kkw8kxSYb29OwlSR1yJbWS3fn7iAmtPB8KBO9L9Z5cE9Y3fqDGwZdzBgnpWUbu63
          zk6jyouzn3Ektj1XXqkP2YsSKfPR8Z3/uwzfH6i8UqB+goAobMu1DDwCYM5cyW6J
          VbUvSn/Tmk+8D7hzeQQ1mhjmGTvl0H6o8Uqn/dRcHKW60Gumbm2D2AESpDgD9zaC
          46qHAoIBAHGN87g2xulyp5AeUU2EOOoM8jsZqETgIMEQ3UQcSn45MF9B2p12R0IP
          PgNSAMa7nv8zHy36YaCyTN9lIN5sygdhyaZnuSabwdyQdI7d/ulu39Lv80HU4RMW
          /e+1SNPk2nDnXMu1YSQ4h7QBvjVfWDdrJb5QJEsE04yngZzyvA+9qU+CLj3nwq6c
          /BzefCYrOediQiaUWOsAmHBYT8tmdZVPO2dx8B7PYH5N1BrP22Ht4rAmH+oDSL87
          QHt2fZrjMZ+sQ75MI4hQc/df1GGBwhtnJ9T6sIfHJlNg+lzAz6JDT9UxkpN2iBaq
          MAbqzjWqf2aKS255dfswfBE4mfAFqKECggEAAUmImdaJ/+YnszudMN6T+YfD0KkB
          siZxvwA2Liy2RPC7aRnoHyNgjgbJFQiz9JTIQ3UM5P2twPjUKD9E/SNtxXCJAkSj
          EEVolBGQNTCTrtItMhy7Wvhwdp3uGNpq8ZWOCZbmrhz4bie3LwZDECkLT6b8cq3i
          1CG3I5w61RBgfE5czGdilzPg3b69ik9frF3urpphUykSpQhezv3eHliQSihIczk+
          M4Giz1LX9q/ZGuea/Gz3tus5WkFsCAsC6ocfS8aFczRJwqBUT9vGXecTf1lB8l4Q
          ySwUvkdFyatQC79PmoZHZRWsijsQeENQum4L8rDaV1ElHJUg+51t7b3Wpg==
          -----END RSA PRIVATE KEY-----
