logging:
  level:
    io.github.tiscs.scp: debug
server:
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}?currentSchema=public
  devtools:
    add-properties: true
    livereload:
      enabled: true
