logging:
  level:
    io.github.tiscs.scp: debug
server:
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.application.name}?useSSL=false&serverTimezone=GMT%2B8
  devtools:
    add-properties: true
    livereload:
      enabled: true