logging:
  level:
    io.github.tiscs.scp: debug
    Exposed: debug
server:
  use-forward-headers: false
management:
  health:
    redis:
      enabled: false
spring:
  session:
    store-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}?currentSchema=public
  devtools:
    add-properties: true
    livereload:
      enabled: true
  cloud:
    config:
      allow-override: true
      override-system-properties: false
      override-none: true
feign:
  client:
    config:
      default:
        loggerLevel: full
