spring:
  datasource:
    username: ${SCP_MYSQL_USERNAME}
    password: ${SCP_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: false
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    rest:
      basePath: /$data
      defaultPageSize: 10
      maxPageSize: 1000
logging:
  level:
    io.github.tiscs.scp: info
    # Fix https://github.com/springfox/springfox/issues/1100, https://github.com/swagger-api/swagger-core/issues/1568
    io.swagger.models.parameters.AbstractSerializableParameter: error