server:
  port: 8888
  servlet:
    encoding:
      force: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
spring:
  main:
    banner-mode: off
  application:
    name: scp-config
  cloud:
    config:
      server:
        default-label: ${CONFIG_DEFAULT_LABEL:main}
        git:
          uri: ${CONFIG_REPO_GIT_URI:https://github.com/tiscs/spring-cloud-practices.git}
          username: ${CONFIG_REPO_GIT_USERNAME}
          password: ${CONFIG_REPO_GIT_PASSWORD}
          search-paths: ${CONFIG_REPO_GIT_PATHS:config-repo}
  devtools:
    add-properties: false
    livereload:
      enabled: false
